# Generated by Django 4.2.4 on 2023-10-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='max_points',
            new_name='points',
        ),
    ]
