# Generated by Django 4.2.4 on 2023-10-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_max_points_assignment_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
